class TreeStore:
    def __init__():
        ...

    def getAll() -> list:
        ...

    def getItem(id) -> dict:
        ...

    def getChildren(id) -> list:
        ...

    def getAllParents(id) -> list:
        ...